import { Stage } from '../models/stage.model.js'

const STAGES = [
  // ── A1 — Das Dorf ─────────────────────────────────────────────────────────
  {
    order: 1,
    theme: 'Greetings & Introductions',
    emoji: '👋',
    description: 'Say hello, introduce yourself, and make your first connections in German.',
    cefrLevel: 'A1',
    worldName: 'Das Dorf',
    unlockRequirement: 0,
  },
  {
    order: 2,
    theme: 'Numbers, Dates & Time',
    emoji: '🕐',
    description: 'Count, tell the time, and navigate dates — essential building blocks.',
    cefrLevel: 'A1',
    worldName: 'Das Dorf',
    unlockRequirement: 1,
  },
  {
    order: 3,
    theme: 'Food & Eating Out',
    emoji: '🍔',
    description: 'Order at a café, read a menu, and talk about what you love to eat.',
    cefrLevel: 'A1',
    worldName: 'Das Dorf',
    unlockRequirement: 2,
  },
  {
    order: 4,
    theme: 'Getting Around',
    emoji: '🚇',
    description: 'Take the U-Bahn, ask for directions, and buy tickets confidently.',
    cefrLevel: 'A1',
    worldName: 'Das Dorf',
    unlockRequirement: 3,
  },
  {
    order: 5,
    theme: 'Family & Home',
    emoji: '🏠',
    description: 'Talk about your family, describe where you live, and feel at home.',
    cefrLevel: 'A1',
    worldName: 'Das Dorf',
    unlockRequirement: 4,
  },
  {
    order: 6,
    theme: 'Shopping & Money',
    emoji: '🛍️',
    description: 'Ask for prices, choose sizes, and handle everyday transactions.',
    cefrLevel: 'A1',
    worldName: 'Das Dorf',
    unlockRequirement: 5,
  },
  // ── A1.2 — Die Stadt ──────────────────────────────────────────────────────
  {
    order: 7,
    theme: 'Weather & Seasons',
    emoji: '⛅',
    description: 'Talk about the weather like a local — from sunshine to Regen.',
    cefrLevel: 'A1.2',
    worldName: 'Die Stadt',
    unlockRequirement: 6,
  },
  {
    order: 8,
    theme: 'Health & the Body',
    emoji: '💊',
    description: 'Visit the Arzt, describe symptoms, and pick up medicine at the Apotheke.',
    cefrLevel: 'A1.2',
    worldName: 'Die Stadt',
    unlockRequirement: 7,
  },
  {
    order: 9,
    theme: 'Work & Daily Routine',
    emoji: '💼',
    description: 'Describe your job, your commute, and what a typical day looks like.',
    cefrLevel: 'A1.2',
    worldName: 'Die Stadt',
    unlockRequirement: 8,
  },
  {
    order: 10,
    theme: 'Hobbies & Free Time',
    emoji: '🎸',
    description: 'Talk about sport, music, cinema, and what you do on the weekend.',
    cefrLevel: 'A1.2',
    worldName: 'Die Stadt',
    unlockRequirement: 9,
  },
  {
    order: 11,
    theme: 'Technology & Social Media',
    emoji: '📱',
    description: 'Text, post, and talk about your Handy, apps, and the internet.',
    cefrLevel: 'A1.2',
    worldName: 'Die Stadt',
    unlockRequirement: 10,
  },
  {
    order: 12,
    theme: 'Celebrations & Traditions',
    emoji: '🎉',
    description: 'From Karneval to Geburtstag — celebrate in German.',
    cefrLevel: 'A1.2',
    worldName: 'Die Stadt',
    unlockRequirement: 11,
  },
  // ── A2 — Die Welt ─────────────────────────────────────────────────────────
  {
    order: 13,
    theme: 'Travel & Tourism',
    emoji: '✈️',
    description: 'Book hotels, navigate airports, and explore Germany as a traveller.',
    cefrLevel: 'A2',
    worldName: 'Die Welt',
    unlockRequirement: 12,
  },
  {
    order: 14,
    theme: 'News & Current Events',
    emoji: '📰',
    description: 'Understand simple German headlines and talk about what is happening.',
    cefrLevel: 'A2',
    worldName: 'Die Welt',
    unlockRequirement: 13,
  },
  {
    order: 15,
    theme: 'Food Culture & Recipes',
    emoji: '🥘',
    description: 'Cook German recipes, discuss cuisine, and talk food culture.',
    cefrLevel: 'A2',
    worldName: 'Die Welt',
    unlockRequirement: 14,
  },
  {
    order: 16,
    theme: 'Housing & Neighbourhood',
    emoji: '🏡',
    description: 'Search for a Wohnung, talk to neighbours, and describe your area.',
    cefrLevel: 'A2',
    worldName: 'Die Welt',
    unlockRequirement: 15,
  },
  {
    order: 17,
    theme: 'Nature & Environment',
    emoji: '🌿',
    description: "Talk about parks, seasons, and Germany's love for recycling.",
    cefrLevel: 'A2',
    worldName: 'Die Welt',
    unlockRequirement: 16,
  },
  {
    order: 18,
    theme: 'Plans & Decisions',
    emoji: '📅',
    description: 'Make plans, express preferences, and talk about what you want to do.',
    cefrLevel: 'A2',
    worldName: 'Die Welt',
    unlockRequirement: 17,
  },
  // ── B1 — Das Leben ────────────────────────────────────────────────────────
  {
    order: 19,
    theme: 'Work, Jobs & Career',
    emoji: '🧑‍💻',
    description: 'Write a Bewerbung, nail interviews, and navigate the German workplace.',
    cefrLevel: 'B1',
    worldName: 'Das Leben',
    unlockRequirement: 18,
  },
  {
    order: 20,
    theme: 'German Media & Culture',
    emoji: '🎬',
    description: 'Discuss films, podcasts, and what is trending in German culture.',
    cefrLevel: 'B1',
    worldName: 'Das Leben',
    unlockRequirement: 19,
  },
  {
    order: 21,
    theme: 'Politics & Society',
    emoji: '🗳️',
    description: 'Follow elections, understand the Bundestag, and talk about society.',
    cefrLevel: 'B1',
    worldName: 'Das Leben',
    unlockRequirement: 20,
  },
  {
    order: 22,
    theme: 'Environment & Sustainability',
    emoji: '♻️',
    description: "Discuss Klimawandel, electric cars, and Germany's Energiewende.",
    cefrLevel: 'B1',
    worldName: 'Das Leben',
    unlockRequirement: 21,
  },
  {
    order: 23,
    theme: 'Debate & Opinion',
    emoji: '💬',
    description: 'Express opinions, agree and disagree, and argue a point in German.',
    cefrLevel: 'B1',
    worldName: 'Das Leben',
    unlockRequirement: 22,
  },
  {
    order: 24,
    theme: 'Contemporary Germany',
    emoji: '🗞️',
    description: 'Engage with real current affairs, modern German life, and the news.',
    cefrLevel: 'B1',
    worldName: 'Das Leben',
    unlockRequirement: 23,
  },
] as const

export async function seedStages(): Promise<void> {
  const existing = await Stage.countDocuments({})
  if (existing >= STAGES.length) return

  console.log('[seed] Seeding stages...')
  for (const data of STAGES) {
    await Stage.updateOne({ order: data.order }, { $setOnInsert: data }, { upsert: true })
  }
  console.log(`[seed] ${STAGES.length} stages ready`)
}
