import type { Types } from 'mongoose'
import { VocabularyItem } from '../models/vocabulary-item.model.js'

export async function seedVocabulary(unitIdMap: Map<number, Types.ObjectId>): Promise<void> {
  const count = await VocabularyItem.countDocuments()
  if (count > 0) {
    console.log('Vocabulary already seeded, skipping...')
    return
  }

  const week1Id = unitIdMap.get(1)!
  const week2Id = unitIdMap.get(2)!
  const week3Id = unitIdMap.get(3)!
  const week4Id = unitIdMap.get(4)!

  const vocabularyItems = [
    // Week 1 - Greetings & Introductions
    {
      german: 'hallo',
      article: null,
      wordType: 'phrase' as const,
      english: 'hello',
      exampleGerman: 'Hallo, wie geht es Ihnen?',
      exampleEnglish: 'Hello, how are you?',
      tags: ['A1', 'week1', 'greetings'],
      cefrLevel: 'A1' as const,
      frequencyRank: 1,
      unitId: week1Id,
    },
    {
      german: 'guten Morgen',
      article: null,
      wordType: 'phrase' as const,
      english: 'good morning',
      exampleGerman: 'Guten Morgen! Wie schläfst du?',
      exampleEnglish: 'Good morning! How did you sleep?',
      tags: ['A1', 'week1', 'greetings'],
      cefrLevel: 'A1' as const,
      frequencyRank: 2,
      unitId: week1Id,
    },
    {
      german: 'guten Tag',
      article: null,
      wordType: 'phrase' as const,
      english: 'good day / good afternoon',
      exampleGerman: 'Guten Tag, Herr Müller!',
      exampleEnglish: 'Good day, Mr. Müller!',
      tags: ['A1', 'week1', 'greetings'],
      cefrLevel: 'A1' as const,
      frequencyRank: 3,
      unitId: week1Id,
    },
    {
      german: 'guten Abend',
      article: null,
      wordType: 'phrase' as const,
      english: 'good evening',
      exampleGerman: 'Guten Abend! Kommen Sie herein.',
      exampleEnglish: 'Good evening! Come in.',
      tags: ['A1', 'week1', 'greetings'],
      cefrLevel: 'A1' as const,
      frequencyRank: 4,
      unitId: week1Id,
    },
    {
      german: 'auf Wiedersehen',
      article: null,
      wordType: 'phrase' as const,
      english: 'goodbye (formal)',
      exampleGerman: 'Auf Wiedersehen, bis morgen!',
      exampleEnglish: 'Goodbye, see you tomorrow!',
      tags: ['A1', 'week1', 'greetings'],
      cefrLevel: 'A1' as const,
      frequencyRank: 5,
      unitId: week1Id,
    },
    {
      german: 'tschüss',
      article: null,
      wordType: 'phrase' as const,
      english: 'bye (informal)',
      exampleGerman: 'Tschüss, wir sehen uns!',
      exampleEnglish: 'Bye, see you around!',
      tags: ['A1', 'week1', 'greetings'],
      cefrLevel: 'A1' as const,
      frequencyRank: 6,
      unitId: week1Id,
    },
    {
      german: 'Name',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'name',
      exampleGerman: 'Mein Name ist Anna.',
      exampleEnglish: 'My name is Anna.',
      pluralForm: 'Namen',
      tags: ['A1', 'week1', 'introductions'],
      cefrLevel: 'A1' as const,
      frequencyRank: 7,
      unitId: week1Id,
    },
    {
      german: 'heißen',
      article: null,
      wordType: 'verb' as const,
      english: 'to be called / to be named',
      exampleGerman: 'Ich heiße Thomas. Wie heißen Sie?',
      exampleEnglish: 'My name is Thomas. What is your name?',
      verbForms: { infinitive: 'heißen', pastParticiple: 'geheißen', thirdPersonSingular: 'heißt' },
      tags: ['A1', 'week1', 'introductions'],
      cefrLevel: 'A1' as const,
      frequencyRank: 8,
      unitId: week1Id,
    },
    {
      german: 'kommen',
      article: null,
      wordType: 'verb' as const,
      english: 'to come',
      exampleGerman: 'Woher kommen Sie? Ich komme aus Deutschland.',
      exampleEnglish: 'Where are you from? I come from Germany.',
      verbForms: { infinitive: 'kommen', pastParticiple: 'gekommen', thirdPersonSingular: 'kommt' },
      tags: ['A1', 'week1', 'introductions'],
      cefrLevel: 'A1' as const,
      frequencyRank: 9,
      unitId: week1Id,
    },
    {
      german: 'wohnen',
      article: null,
      wordType: 'verb' as const,
      english: 'to live / to reside',
      exampleGerman: 'Ich wohne in Berlin.',
      exampleEnglish: 'I live in Berlin.',
      verbForms: { infinitive: 'wohnen', pastParticiple: 'gewohnt', thirdPersonSingular: 'wohnt' },
      tags: ['A1', 'week1', 'introductions'],
      cefrLevel: 'A1' as const,
      frequencyRank: 10,
      unitId: week1Id,
    },
    {
      german: 'sprechen',
      article: null,
      wordType: 'verb' as const,
      english: 'to speak',
      exampleGerman: 'Ich spreche Deutsch und Englisch.',
      exampleEnglish: 'I speak German and English.',
      verbForms: {
        infinitive: 'sprechen',
        pastParticiple: 'gesprochen',
        thirdPersonSingular: 'spricht',
      },
      tags: ['A1', 'week1', 'introductions', 'languages'],
      cefrLevel: 'A1' as const,
      frequencyRank: 11,
      unitId: week1Id,
    },
    {
      german: 'Deutsch',
      article: null,
      wordType: 'noun' as const,
      english: 'German (language)',
      exampleGerman: 'Lernen Sie Deutsch? — Ja, ein bisschen.',
      exampleEnglish: 'Are you learning German? — Yes, a little.',
      tags: ['A1', 'week1', 'languages'],
      cefrLevel: 'A1' as const,
      frequencyRank: 12,
      unitId: week1Id,
    },
    {
      german: 'bitte',
      article: null,
      wordType: 'adverb' as const,
      english: "please / you're welcome",
      exampleGerman: 'Ein Kaffee, bitte. — Bitte sehr!',
      exampleEnglish: 'A coffee, please. — Here you go!',
      tags: ['A1', 'week1', 'courtesy'],
      cefrLevel: 'A1' as const,
      frequencyRank: 13,
      unitId: week1Id,
    },
    {
      german: 'danke',
      article: null,
      wordType: 'phrase' as const,
      english: 'thank you',
      exampleGerman: 'Danke schön für Ihre Hilfe!',
      exampleEnglish: 'Thank you very much for your help!',
      tags: ['A1', 'week1', 'courtesy'],
      cefrLevel: 'A1' as const,
      frequencyRank: 14,
      unitId: week1Id,
    },
    {
      german: 'entschuldigung',
      article: null,
      wordType: 'phrase' as const,
      english: 'excuse me / sorry',
      exampleGerman: 'Entschuldigung, wo ist der Bahnhof?',
      exampleEnglish: 'Excuse me, where is the train station?',
      tags: ['A1', 'week1', 'courtesy'],
      cefrLevel: 'A1' as const,
      frequencyRank: 15,
      unitId: week1Id,
    },
    {
      german: 'ja',
      article: null,
      wordType: 'adverb' as const,
      english: 'yes',
      exampleGerman: 'Ja, ich verstehe.',
      exampleEnglish: 'Yes, I understand.',
      tags: ['A1', 'week1', 'basics'],
      cefrLevel: 'A1' as const,
      frequencyRank: 16,
      unitId: week1Id,
    },
    {
      german: 'nein',
      article: null,
      wordType: 'adverb' as const,
      english: 'no',
      exampleGerman: 'Nein, das stimmt nicht.',
      exampleEnglish: 'No, that is not correct.',
      tags: ['A1', 'week1', 'basics'],
      cefrLevel: 'A1' as const,
      frequencyRank: 17,
      unitId: week1Id,
    },
    // Week 2 - Family & Daily Life
    {
      german: 'Familie',
      article: 'die' as const,
      wordType: 'noun' as const,
      english: 'family',
      exampleGerman: 'Meine Familie ist sehr groß.',
      exampleEnglish: 'My family is very large.',
      pluralForm: 'Familien',
      tags: ['A1', 'week2', 'family'],
      cefrLevel: 'A1' as const,
      frequencyRank: 18,
      unitId: week2Id,
    },
    {
      german: 'Mutter',
      article: 'die' as const,
      wordType: 'noun' as const,
      english: 'mother',
      exampleGerman: 'Meine Mutter arbeitet als Ärztin.',
      exampleEnglish: 'My mother works as a doctor.',
      pluralForm: 'Mütter',
      tags: ['A1', 'week2', 'family'],
      cefrLevel: 'A1' as const,
      frequencyRank: 19,
      unitId: week2Id,
    },
    {
      german: 'Vater',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'father',
      exampleGerman: 'Mein Vater spielt gerne Fußball.',
      exampleEnglish: 'My father likes to play football.',
      pluralForm: 'Väter',
      tags: ['A1', 'week2', 'family'],
      cefrLevel: 'A1' as const,
      frequencyRank: 20,
      unitId: week2Id,
    },
    {
      german: 'Bruder',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'brother',
      exampleGerman: 'Ich habe einen Bruder und eine Schwester.',
      exampleEnglish: 'I have one brother and one sister.',
      pluralForm: 'Brüder',
      tags: ['A1', 'week2', 'family'],
      cefrLevel: 'A1' as const,
      frequencyRank: 21,
      unitId: week2Id,
    },
    {
      german: 'Schwester',
      article: 'die' as const,
      wordType: 'noun' as const,
      english: 'sister',
      exampleGerman: 'Meine Schwester wohnt in München.',
      exampleEnglish: 'My sister lives in Munich.',
      pluralForm: 'Schwestern',
      tags: ['A1', 'week2', 'family'],
      cefrLevel: 'A1' as const,
      frequencyRank: 22,
      unitId: week2Id,
    },
    {
      german: 'Kind',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'child',
      exampleGerman: 'Das Kind spielt im Park.',
      exampleEnglish: 'The child plays in the park.',
      pluralForm: 'Kinder',
      tags: ['A1', 'week2', 'family'],
      cefrLevel: 'A1' as const,
      frequencyRank: 23,
      unitId: week2Id,
    },
    {
      german: 'arbeiten',
      article: null,
      wordType: 'verb' as const,
      english: 'to work',
      exampleGerman: 'Ich arbeite von neun bis fünf.',
      exampleEnglish: 'I work from nine to five.',
      verbForms: {
        infinitive: 'arbeiten',
        pastParticiple: 'gearbeitet',
        thirdPersonSingular: 'arbeitet',
      },
      tags: ['A1', 'week2', 'daily-life'],
      cefrLevel: 'A1' as const,
      frequencyRank: 24,
      unitId: week2Id,
    },
    {
      german: 'schlafen',
      article: null,
      wordType: 'verb' as const,
      english: 'to sleep',
      exampleGerman: 'Ich schlafe acht Stunden pro Nacht.',
      exampleEnglish: 'I sleep eight hours per night.',
      verbForms: {
        infinitive: 'schlafen',
        pastParticiple: 'geschlafen',
        thirdPersonSingular: 'schläft',
      },
      tags: ['A1', 'week2', 'daily-life'],
      cefrLevel: 'A1' as const,
      frequencyRank: 25,
      unitId: week2Id,
    },
    {
      german: 'essen',
      article: null,
      wordType: 'verb' as const,
      english: 'to eat',
      exampleGerman: 'Was isst du zum Frühstück?',
      exampleEnglish: 'What do you eat for breakfast?',
      verbForms: { infinitive: 'essen', pastParticiple: 'gegessen', thirdPersonSingular: 'isst' },
      tags: ['A1', 'week2', 'daily-life', 'food'],
      cefrLevel: 'A1' as const,
      frequencyRank: 26,
      unitId: week2Id,
    },
    {
      german: 'trinken',
      article: null,
      wordType: 'verb' as const,
      english: 'to drink',
      exampleGerman: 'Ich trinke morgens Kaffee.',
      exampleEnglish: 'I drink coffee in the morning.',
      verbForms: {
        infinitive: 'trinken',
        pastParticiple: 'getrunken',
        thirdPersonSingular: 'trinkt',
      },
      tags: ['A1', 'week2', 'daily-life', 'food'],
      cefrLevel: 'A1' as const,
      frequencyRank: 27,
      unitId: week2Id,
    },
    {
      german: 'gehen',
      article: null,
      wordType: 'verb' as const,
      english: 'to go / to walk',
      exampleGerman: 'Ich gehe jeden Tag zur Arbeit.',
      exampleEnglish: 'I go to work every day.',
      verbForms: { infinitive: 'gehen', pastParticiple: 'gegangen', thirdPersonSingular: 'geht' },
      tags: ['A1', 'week2', 'daily-life'],
      cefrLevel: 'A1' as const,
      frequencyRank: 28,
      unitId: week2Id,
    },
    {
      german: 'lesen',
      article: null,
      wordType: 'verb' as const,
      english: 'to read',
      exampleGerman: 'Er liest jeden Abend ein Buch.',
      exampleEnglish: 'He reads a book every evening.',
      verbForms: { infinitive: 'lesen', pastParticiple: 'gelesen', thirdPersonSingular: 'liest' },
      tags: ['A1', 'week2', 'daily-life'],
      cefrLevel: 'A1' as const,
      frequencyRank: 29,
      unitId: week2Id,
    },
    {
      german: 'Haus',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'house',
      exampleGerman: 'Das Haus ist sehr schön.',
      exampleEnglish: 'The house is very beautiful.',
      pluralForm: 'Häuser',
      tags: ['A1', 'week2', 'home'],
      cefrLevel: 'A1' as const,
      frequencyRank: 30,
      unitId: week2Id,
    },
    // Week 3 - Food & Shopping
    {
      german: 'Brot',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'bread',
      exampleGerman: 'Ich kaufe jeden Morgen frisches Brot.',
      exampleEnglish: 'I buy fresh bread every morning.',
      pluralForm: 'Brote',
      tags: ['A1', 'week3', 'food'],
      cefrLevel: 'A1' as const,
      frequencyRank: 31,
      unitId: week3Id,
    },
    {
      german: 'Kaffee',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'coffee',
      exampleGerman: 'Die Frau trinkt Kaffee mit Milch.',
      exampleEnglish: 'The woman drinks coffee with milk.',
      tags: ['A1', 'week3', 'food', 'drinks'],
      cefrLevel: 'A1' as const,
      frequencyRank: 32,
      unitId: week3Id,
    },
    {
      german: 'Wasser',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'water',
      exampleGerman: 'Ein Glas Wasser, bitte.',
      exampleEnglish: 'A glass of water, please.',
      tags: ['A1', 'week3', 'food', 'drinks'],
      cefrLevel: 'A1' as const,
      frequencyRank: 33,
      unitId: week3Id,
    },
    {
      german: 'Fleisch',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'meat',
      exampleGerman: 'Ich esse kein Fleisch — ich bin Vegetarier.',
      exampleEnglish: "I don't eat meat — I am a vegetarian.",
      tags: ['A1', 'week3', 'food'],
      cefrLevel: 'A1' as const,
      frequencyRank: 34,
      unitId: week3Id,
    },
    {
      german: 'Gemüse',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'vegetables',
      exampleGerman: 'Frisches Gemüse ist sehr gesund.',
      exampleEnglish: 'Fresh vegetables are very healthy.',
      tags: ['A1', 'week3', 'food'],
      cefrLevel: 'A1' as const,
      frequencyRank: 35,
      unitId: week3Id,
    },
    {
      german: 'Obst',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'fruit',
      exampleGerman: 'Sie isst jeden Tag viel Obst.',
      exampleEnglish: 'She eats a lot of fruit every day.',
      tags: ['A1', 'week3', 'food'],
      cefrLevel: 'A1' as const,
      frequencyRank: 36,
      unitId: week3Id,
    },
    {
      german: 'kaufen',
      article: null,
      wordType: 'verb' as const,
      english: 'to buy',
      exampleGerman: 'Ich kaufe ein neues Buch.',
      exampleEnglish: 'I am buying a new book.',
      verbForms: { infinitive: 'kaufen', pastParticiple: 'gekauft', thirdPersonSingular: 'kauft' },
      tags: ['A1', 'week3', 'shopping'],
      cefrLevel: 'A1' as const,
      frequencyRank: 37,
      unitId: week3Id,
    },
    {
      german: 'kosten',
      article: null,
      wordType: 'verb' as const,
      english: 'to cost',
      exampleGerman: 'Was kostet das? — Es kostet fünf Euro.',
      exampleEnglish: 'How much does this cost? — It costs five euros.',
      verbForms: {
        infinitive: 'kosten',
        pastParticiple: 'gekostet',
        thirdPersonSingular: 'kostet',
      },
      tags: ['A1', 'week3', 'shopping'],
      cefrLevel: 'A1' as const,
      frequencyRank: 38,
      unitId: week3Id,
    },
    {
      german: 'Markt',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'market',
      exampleGerman: 'Jeden Samstag gehe ich auf den Markt.',
      exampleEnglish: 'Every Saturday I go to the market.',
      pluralForm: 'Märkte',
      tags: ['A1', 'week3', 'shopping', 'places'],
      cefrLevel: 'A1' as const,
      frequencyRank: 39,
      unitId: week3Id,
    },
    {
      german: 'Geld',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'money',
      exampleGerman: 'Haben Sie Geld dabei?',
      exampleEnglish: 'Do you have money with you?',
      tags: ['A1', 'week3', 'shopping'],
      cefrLevel: 'A1' as const,
      frequencyRank: 40,
      unitId: week3Id,
    },
    {
      german: 'billig',
      article: null,
      wordType: 'adjective' as const,
      english: 'cheap / inexpensive',
      exampleGerman: 'Das Hemd ist sehr billig.',
      exampleEnglish: 'The shirt is very cheap.',
      tags: ['A1', 'week3', 'shopping', 'adjectives'],
      cefrLevel: 'A1' as const,
      frequencyRank: 41,
      unitId: week3Id,
    },
    {
      german: 'teuer',
      article: null,
      wordType: 'adjective' as const,
      english: 'expensive',
      exampleGerman: 'Das Restaurant ist zu teuer für mich.',
      exampleEnglish: 'The restaurant is too expensive for me.',
      tags: ['A1', 'week3', 'shopping', 'adjectives'],
      cefrLevel: 'A1' as const,
      frequencyRank: 42,
      unitId: week3Id,
    },
    {
      german: 'Tisch',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'table',
      exampleGerman: 'Der Tisch ist groß und braun.',
      exampleEnglish: 'The table is big and brown.',
      pluralForm: 'Tische',
      tags: ['A1', 'week3', 'furniture', 'restaurant'],
      cefrLevel: 'A1' as const,
      frequencyRank: 43,
      unitId: week3Id,
    },
    // Week 4 - Places & Transport
    {
      german: 'Bahnhof',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'train station',
      exampleGerman: 'Der Bahnhof ist in der Stadtmitte.',
      exampleEnglish: 'The train station is in the city center.',
      pluralForm: 'Bahnhöfe',
      tags: ['A1', 'week4', 'places', 'transport'],
      cefrLevel: 'A1' as const,
      frequencyRank: 44,
      unitId: week4Id,
    },
    {
      german: 'Bus',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'bus',
      exampleGerman: 'Ich fahre mit dem Bus zur Schule.',
      exampleEnglish: 'I take the bus to school.',
      pluralForm: 'Busse',
      tags: ['A1', 'week4', 'transport'],
      cefrLevel: 'A1' as const,
      frequencyRank: 45,
      unitId: week4Id,
    },
    {
      german: 'Straße',
      article: 'die' as const,
      wordType: 'noun' as const,
      english: 'street / road',
      exampleGerman: 'Die Hauptstraße ist sehr breit.',
      exampleEnglish: 'The main street is very wide.',
      pluralForm: 'Straßen',
      tags: ['A1', 'week4', 'places'],
      cefrLevel: 'A1' as const,
      frequencyRank: 46,
      unitId: week4Id,
    },
    {
      german: 'Schule',
      article: 'die' as const,
      wordType: 'noun' as const,
      english: 'school',
      exampleGerman: 'Die Kinder gehen jeden Tag in die Schule.',
      exampleEnglish: 'The children go to school every day.',
      pluralForm: 'Schulen',
      tags: ['A1', 'week4', 'places', 'education'],
      cefrLevel: 'A1' as const,
      frequencyRank: 47,
      unitId: week4Id,
    },
    {
      german: 'Krankenhaus',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'hospital',
      exampleGerman: 'Das Krankenhaus ist neben der Post.',
      exampleEnglish: 'The hospital is next to the post office.',
      pluralForm: 'Krankenhäuser',
      tags: ['A1', 'week4', 'places'],
      cefrLevel: 'A1' as const,
      frequencyRank: 48,
      unitId: week4Id,
    },
    {
      german: 'fahren',
      article: null,
      wordType: 'verb' as const,
      english: 'to drive / to travel',
      exampleGerman: 'Ich fahre mit dem Zug nach Hamburg.',
      exampleEnglish: 'I am travelling by train to Hamburg.',
      verbForms: { infinitive: 'fahren', pastParticiple: 'gefahren', thirdPersonSingular: 'fährt' },
      tags: ['A1', 'week4', 'transport'],
      cefrLevel: 'A1' as const,
      frequencyRank: 49,
      unitId: week4Id,
    },
    {
      german: 'links',
      article: null,
      wordType: 'adverb' as const,
      english: 'left / to the left',
      exampleGerman: 'Biegen Sie links ab.',
      exampleEnglish: 'Turn left.',
      tags: ['A1', 'week4', 'directions'],
      cefrLevel: 'A1' as const,
      frequencyRank: 50,
      unitId: week4Id,
    },
    {
      german: 'rechts',
      article: null,
      wordType: 'adverb' as const,
      english: 'right / to the right',
      exampleGerman: 'Das Hotel ist auf der rechten Seite.',
      exampleEnglish: 'The hotel is on the right side.',
      tags: ['A1', 'week4', 'directions'],
      cefrLevel: 'A1' as const,
      frequencyRank: 51,
      unitId: week4Id,
    },
    {
      german: 'geradeaus',
      article: null,
      wordType: 'adverb' as const,
      english: 'straight ahead',
      exampleGerman: 'Gehen Sie geradeaus bis zur Ampel.',
      exampleEnglish: 'Go straight ahead to the traffic light.',
      tags: ['A1', 'week4', 'directions'],
      cefrLevel: 'A1' as const,
      frequencyRank: 52,
      unitId: week4Id,
    },
    {
      german: 'weit',
      article: null,
      wordType: 'adjective' as const,
      english: 'far',
      exampleGerman: 'Ist der Bahnhof weit von hier?',
      exampleEnglish: 'Is the train station far from here?',
      tags: ['A1', 'week4', 'directions'],
      cefrLevel: 'A1' as const,
      frequencyRank: 53,
      unitId: week4Id,
    },
    {
      german: 'nah',
      article: null,
      wordType: 'adjective' as const,
      english: 'near / close',
      exampleGerman: 'Die U-Bahn-Station ist nah.',
      exampleEnglish: 'The subway station is close.',
      tags: ['A1', 'week4', 'directions'],
      cefrLevel: 'A1' as const,
      frequencyRank: 54,
      unitId: week4Id,
    },
    {
      german: 'Zug',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'train',
      exampleGerman: 'Der Zug fährt um acht Uhr ab.',
      exampleEnglish: "The train departs at eight o'clock.",
      pluralForm: 'Züge',
      tags: ['A1', 'week4', 'transport'],
      cefrLevel: 'A1' as const,
      frequencyRank: 55,
      unitId: week4Id,
    },
    {
      german: 'Flugzeug',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'airplane',
      exampleGerman: 'Das Flugzeug landet in zwei Stunden.',
      exampleEnglish: 'The airplane lands in two hours.',
      pluralForm: 'Flugzeuge',
      tags: ['A1', 'week4', 'transport'],
      cefrLevel: 'A1' as const,
      frequencyRank: 56,
      unitId: week4Id,
    },
    {
      german: 'Ticket',
      article: 'das' as const,
      wordType: 'noun' as const,
      english: 'ticket',
      exampleGerman: 'Ich brauche ein Ticket nach Berlin.',
      exampleEnglish: 'I need a ticket to Berlin.',
      pluralForm: 'Tickets',
      tags: ['A1', 'week4', 'transport'],
      cefrLevel: 'A1' as const,
      frequencyRank: 57,
      unitId: week4Id,
    },
    // Extra items to reach 60+
    {
      german: 'groß',
      article: null,
      wordType: 'adjective' as const,
      english: 'big / tall',
      exampleGerman: 'Das Gebäude ist sehr groß.',
      exampleEnglish: 'The building is very big.',
      tags: ['A1', 'week1', 'adjectives'],
      cefrLevel: 'A1' as const,
      frequencyRank: 58,
      unitId: week1Id,
    },
    {
      german: 'klein',
      article: null,
      wordType: 'adjective' as const,
      english: 'small / short',
      exampleGerman: 'Die Wohnung ist klein, aber gemütlich.',
      exampleEnglish: 'The apartment is small but cozy.',
      tags: ['A1', 'week1', 'adjectives'],
      cefrLevel: 'A1' as const,
      frequencyRank: 59,
      unitId: week1Id,
    },
    {
      german: 'und',
      article: null,
      wordType: 'conjunction' as const,
      english: 'and',
      exampleGerman: 'Ich lerne Deutsch und Spanisch.',
      exampleEnglish: 'I am learning German and Spanish.',
      tags: ['A1', 'week1', 'basics'],
      cefrLevel: 'A1' as const,
      frequencyRank: 60,
      unitId: week1Id,
    },
    {
      german: 'oder',
      article: null,
      wordType: 'conjunction' as const,
      english: 'or',
      exampleGerman: 'Tee oder Kaffee?',
      exampleEnglish: 'Tea or coffee?',
      tags: ['A1', 'week1', 'basics'],
      cefrLevel: 'A1' as const,
      frequencyRank: 61,
      unitId: week1Id,
    },
    {
      german: 'Student',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'student (male)',
      exampleGerman: 'Er ist Student an der Universität Berlin.',
      exampleEnglish: 'He is a student at Berlin University.',
      pluralForm: 'Studenten',
      tags: ['A1', 'week1', 'professions'],
      cefrLevel: 'A1' as const,
      frequencyRank: 62,
      unitId: week1Id,
    },
    {
      german: 'Frau',
      article: 'die' as const,
      wordType: 'noun' as const,
      english: 'woman / Mrs.',
      exampleGerman: 'Die Frau trinkt Kaffee.',
      exampleEnglish: 'The woman drinks coffee.',
      pluralForm: 'Frauen',
      tags: ['A1', 'week1', 'people'],
      cefrLevel: 'A1' as const,
      frequencyRank: 63,
      unitId: week1Id,
    },
    {
      german: 'Mann',
      article: 'der' as const,
      wordType: 'noun' as const,
      english: 'man / husband',
      exampleGerman: 'Der Mann liest die Zeitung.',
      exampleEnglish: 'The man reads the newspaper.',
      pluralForm: 'Männer',
      tags: ['A1', 'week1', 'people'],
      cefrLevel: 'A1' as const,
      frequencyRank: 64,
      unitId: week1Id,
    },
    {
      german: 'heute',
      article: null,
      wordType: 'adverb' as const,
      english: 'today',
      exampleGerman: 'Was machst du heute Abend?',
      exampleEnglish: 'What are you doing tonight?',
      tags: ['A1', 'week2', 'time'],
      cefrLevel: 'A1' as const,
      frequencyRank: 65,
      unitId: week2Id,
    },
    {
      german: 'morgen',
      article: null,
      wordType: 'adverb' as const,
      english: 'tomorrow',
      exampleGerman: 'Morgen gehe ich zum Arzt.',
      exampleEnglish: 'Tomorrow I am going to the doctor.',
      tags: ['A1', 'week2', 'time'],
      cefrLevel: 'A1' as const,
      frequencyRank: 66,
      unitId: week2Id,
    },
  ]

  await VocabularyItem.insertMany(vocabularyItems)
  console.log(`Seeded ${vocabularyItems.length} vocabulary items`)
}
