import type { CurriculumUnitWithProgress } from '@lernen/shared'
import { Types } from 'mongoose'
import { CurriculumUnit } from '../models/curriculum-unit.model.js'
import { type ILesson, Lesson } from '../models/lesson.model.js'
import { UserLessonProgress } from '../models/user-lesson-progress.model.js'

export async function getCurriculumWithProgress(
  userId: string,
): Promise<CurriculumUnitWithProgress[]> {
  const units = await CurriculumUnit.find({}).sort({ order: 1 })
  const userObjId = new Types.ObjectId(userId)

  const results: CurriculumUnitWithProgress[] = []

  for (const unit of units) {
    const lessons = await Lesson.find({ unitId: unit._id }).sort({ orderInUnit: 1 })

    const progressRecords = await UserLessonProgress.find({
      userId: userObjId,
      lessonId: { $in: lessons.map((l) => l._id) },
    })

    const progressMap = new Map(progressRecords.map((p) => [p.lessonId.toString(), p]))

    const completedLessons = progressRecords.filter((p) => p.status === 'completed').length
    const totalLessons = lessons.length
    const percentComplete =
      totalLessons > 0 ? Math.round((completedLessons / totalLessons) * 100) : 0

    const lessonsWithProgress = lessons.map((lesson) => {
      const progress = progressMap.get(lesson._id.toString())
      return {
        _id: lesson._id.toString(),
        stageId: lesson.stageId?.toString() ?? undefined,
        type: lesson.type,
        title: lesson.title,
        orderInUnit: lesson.orderInUnit,
        estimatedMinutes: lesson.estimatedMinutes,
        content: lesson.content,
        progressStatus: progress?.status ?? 'not_started',
        score: progress?.score ?? 0,
      }
    })

    results.push({
      _id: unit._id.toString(),
      weekNumber: unit.weekNumber,
      cefrLevel: unit.cefrLevel,
      title: unit.title,
      description: unit.description,
      vocabularyTheme: unit.vocabularyTheme,
      grammarFocus: unit.grammarFocus,
      estimatedMinutes: unit.estimatedMinutes,
      order: unit.order,
      progress: { completedLessons, totalLessons, percentComplete },
      lessons: lessonsWithProgress,
    })
  }

  return results
}

export async function getNextLesson(userId: string): Promise<ILesson | null> {
  const userObjId = new Types.ObjectId(userId)
  const allLessons = await Lesson.find({}).sort({ stageId: 1, orderInUnit: 1 })

  for (const lesson of allLessons) {
    const progress = await UserLessonProgress.findOne({
      userId: userObjId,
      lessonId: lesson._id,
    })

    if (!progress || progress.status !== 'completed') {
      return lesson
    }
  }

  // All seeded lessons done — buffer should have been pre-generated by BullMQ.
  // If nothing is ready yet (e.g. first time, Ollama still warming up), return null
  // and the dashboard will show "no lesson available" gracefully.
  return null
}

export async function getLessonById(id: string): Promise<ILesson | null> {
  return Lesson.findById(id)
}

export async function startLesson(userId: string, lessonId: string): Promise<void> {
  await UserLessonProgress.findOneAndUpdate(
    {
      userId: new Types.ObjectId(userId),
      lessonId: new Types.ObjectId(lessonId),
    },
    {
      $setOnInsert: { status: 'in_progress' },
      $inc: { attemptCount: 0 },
    },
    { upsert: true },
  )

  await UserLessonProgress.findOneAndUpdate(
    {
      userId: new Types.ObjectId(userId),
      lessonId: new Types.ObjectId(lessonId),
      status: 'not_started',
    },
    { $set: { status: 'in_progress' } },
  )
}

export async function completeLesson(
  userId: string,
  lessonId: string,
  score: number,
  timeSpentSeconds: number,
): Promise<void> {
  await UserLessonProgress.findOneAndUpdate(
    {
      userId: new Types.ObjectId(userId),
      lessonId: new Types.ObjectId(lessonId),
    },
    {
      $set: {
        status: 'completed',
        score,
        completedAt: new Date(),
        timeSpentSeconds,
      },
      $inc: { attemptCount: 1 },
    },
    { upsert: true },
  )
}
