import type { Exercise, GeneratedSessionDTO } from '@lernen/shared'
import { checkAnswer } from '@lernen/shared'
import { Link, useNavigate } from '@tanstack/react-router'
import { ArrowLeft, ArrowRight, Brain, CheckCircle, Loader2, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { ExerciseRenderer } from '../components/ExerciseRenderer'
import { AppLayout } from '../components/layout/AppLayout'
import { ProgressBar } from '../components/ProgressBar'
import { useCompleteSession, useGenerateExercises } from '../hooks/use-practice'
import { cn } from '../lib/utils'

interface AnswerRecord {
  exerciseId: string
  answer: string
  timeSpentMs: number
  isCorrect: boolean
  isTypo: boolean
  correctAnswer: string
  explanation?: string
}

export function PracticePage() {
  const _navigate = useNavigate()
  const { mutate: generate, isPending: isGenerating } = useGenerateExercises()
  const { mutate: completeSession, isPending: isCompleting } = useCompleteSession()

  const [session, setSession] = useState<GeneratedSessionDTO | null>(null)
  const [phase, setPhase] = useState<'idle' | 'exercises' | 'results'>('idle')
  const [currentExIndex, setCurrentExIndex] = useState(0)
  const [answers, setAnswers] = useState<AnswerRecord[]>([])
  const [currentResult, setCurrentResult] = useState<{
    isCorrect: boolean
    isTypo: boolean
    correctAnswer: string
    explanation?: string
  } | null>(null)
  const [finalResult, setFinalResult] = useState<{
    score: number
    xpEarned: number
    correctAnswers: number
    totalExercises: number
  } | null>(null)

  const handleGenerate = () => {
    generate(undefined, {
      onSuccess: (newSession) => {
        setSession(newSession)
        setPhase('exercises')
        setCurrentExIndex(0)
        setAnswers([])
        setCurrentResult(null)
      },
      onError: () => {},
    })
  }

  const exercises = session?.exercises ?? []
  const currentExercise = exercises[currentExIndex] as Exercise | undefined
  const progress = exercises.length > 0 ? (currentExIndex / exercises.length) * 100 : 0

  const handleAnswer = (answer: string, timeSpentMs: number) => {
    if (!currentExercise) return

    const { isCorrect, isTypo } = checkAnswer(currentExercise.type, answer, currentExercise.answer)

    setCurrentResult({
      isCorrect,
      isTypo,
      correctAnswer: currentExercise.answer,
      explanation: currentExercise.explanation,
    })

    setAnswers((prev) => [
      ...prev,
      {
        exerciseId: currentExercise.id,
        answer,
        timeSpentMs,
        isCorrect,
        isTypo,
        correctAnswer: currentExercise.answer,
        explanation: currentExercise.explanation,
      },
    ])
  }

  const handleNext = () => {
    setCurrentResult(null)
    if (currentExIndex < exercises.length - 1) {
      setCurrentExIndex((i) => i + 1)
    } else {
      const allAnswers = answers.map((a) => ({
        exerciseId: a.exerciseId,
        answer: a.answer,
        timeSpentMs: a.timeSpentMs,
      }))
      completeSession(
        { sessionId: session?._id ?? '', answers: allAnswers },
        {
          onSuccess: (result) => {
            setFinalResult(result)
            setPhase('results')
          },
        },
      )
    }
  }

  // Idle: landing screen
  if (phase === 'idle') {
    return (
      <AppLayout>
        <div className="flex items-center justify-center min-h-[70vh] px-6">
          <div className="text-center max-w-md w-full">
            <div className="w-20 h-20 bg-amber-400/10 border border-amber-400/30 rounded-2xl flex items-center justify-center mx-auto mb-6">
              <Brain size={40} className="text-amber-400" />
            </div>
            <h1 className="text-2xl font-bold text-white mb-3">AI Practice</h1>
            <p className="text-slate-400 mb-2">
              Exercises generated by AI based on your progress — reading, speaking, translation, and
              more.
            </p>
            <p className="text-slate-500 text-sm mb-8">
              Each session is unique and tailored to where you are.
            </p>

            <button
              type="button"
              onClick={handleGenerate}
              disabled={isGenerating}
              className="w-full py-4 bg-amber-400 text-slate-950 rounded-xl font-semibold text-lg hover:bg-amber-500 transition-colors flex items-center justify-center gap-2 disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {isGenerating ? (
                <>
                  <Loader2 size={20} className="animate-spin" />
                  Generating exercises...
                </>
              ) : (
                <>
                  <Sparkles size={20} />
                  Generate Practice Session
                </>
              )}
            </button>

            <Link
              to="/dashboard"
              className="block mt-4 text-sm text-slate-500 hover:text-slate-300 transition-colors"
            >
              Back to Dashboard
            </Link>
          </div>
        </div>
      </AppLayout>
    )
  }

  // Exercises phase
  if (phase === 'exercises' && currentExercise) {
    return (
      <AppLayout>
        <div className="px-6 py-8 max-w-2xl mx-auto">
          <div className="flex items-center justify-between mb-6">
            <button
              type="button"
              onClick={() => setPhase('idle')}
              className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors text-sm"
            >
              <ArrowLeft size={16} />
              Exit
            </button>
            <div className="text-center">
              <p className="text-xs text-slate-500">{session?.topic}</p>
              <p className="text-sm text-slate-400">
                {currentExIndex + 1} / {exercises.length}
              </p>
            </div>
            <span className="px-2 py-1 bg-amber-400/10 border border-amber-400/20 text-amber-400 text-xs rounded-full">
              AI
            </span>
          </div>

          <ProgressBar value={progress} max={100} className="mb-8" />

          <div className="mb-6">
            <span className="px-2.5 py-1 bg-slate-800 text-slate-400 text-xs rounded-full font-medium uppercase tracking-wide">
              {currentExercise.type.replace(/_/g, ' ')}
            </span>
          </div>

          <ExerciseRenderer
            key={currentExercise.id}
            exercise={currentExercise}
            onAnswer={handleAnswer}
            showResult={!!currentResult}
            isCorrect={currentResult?.isCorrect}
            isTypo={currentResult?.isTypo}
            correctAnswer={currentResult?.correctAnswer}
            wrongFeedback={
              currentResult && !currentResult.isCorrect ? currentExercise.wrongFeedback : undefined
            }
            correctFeedback={currentResult?.isCorrect ? currentExercise.correctFeedback : undefined}
          />

          {currentResult && (
            <button
              type="button"
              onClick={handleNext}
              disabled={isCompleting}
              className={cn(
                'w-full mt-6 py-3 rounded-xl font-semibold transition-colors flex items-center justify-center gap-2',
                currentResult.isCorrect
                  ? 'bg-emerald-500 text-white hover:bg-emerald-600'
                  : 'bg-slate-700 text-white hover:bg-slate-600',
              )}
            >
              {isCompleting ? (
                <Loader2 size={18} className="animate-spin" />
              ) : currentExIndex < exercises.length - 1 ? (
                <>
                  Continue <ArrowRight size={18} />
                </>
              ) : (
                <>
                  Finish <CheckCircle size={18} />
                </>
              )}
            </button>
          )}
        </div>
      </AppLayout>
    )
  }

  // Results phase
  if (phase === 'results' && finalResult) {
    const scoreColor =
      finalResult.score >= 80
        ? 'text-emerald-400'
        : finalResult.score >= 60
          ? 'text-amber-400'
          : 'text-red-400'

    return (
      <AppLayout>
        <div className="flex items-center justify-center min-h-[60vh] px-6">
          <div className="text-center max-w-md w-full">
            <div
              className={cn(
                'w-24 h-24 rounded-full flex items-center justify-center mx-auto mb-6 border-4',
                finalResult.score >= 80
                  ? 'bg-emerald-500/10 border-emerald-500/30'
                  : finalResult.score >= 60
                    ? 'bg-amber-400/10 border-amber-400/30'
                    : 'bg-red-500/10 border-red-500/30',
              )}
            >
              <span className={cn('text-3xl font-bold', scoreColor)}>{finalResult.score}%</span>
            </div>

            <h2 className="text-2xl font-bold text-white mb-2">Practice Complete!</h2>
            <p className="text-slate-400 mb-8">
              {finalResult.correctAnswers} of {finalResult.totalExercises} correct
            </p>

            <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 mb-8">
              <div className="grid grid-cols-2 gap-6">
                <div className="text-center">
                  <p className={cn('text-3xl font-bold', scoreColor)}>{finalResult.score}%</p>
                  <p className="text-xs text-slate-400 mt-1">Score</p>
                </div>
                <div className="text-center">
                  <p className="text-3xl font-bold text-amber-400">+{finalResult.xpEarned}</p>
                  <p className="text-xs text-slate-400 mt-1">XP earned</p>
                </div>
              </div>
            </div>

            <div className="flex gap-3">
              <Link
                to="/dashboard"
                className="flex-1 py-3 bg-slate-800 border border-slate-700 text-white rounded-xl font-medium hover:bg-slate-700 transition-colors text-center"
              >
                Dashboard
              </Link>
              <button
                type="button"
                onClick={() => {
                  setPhase('idle')
                  setSession(null)
                  setFinalResult(null)
                }}
                className="flex-1 py-3 bg-amber-400 text-slate-950 rounded-xl font-semibold hover:bg-amber-500 transition-colors flex items-center justify-center gap-2"
              >
                <Sparkles size={16} />
                Practice Again
              </button>
            </div>
          </div>
        </div>
      </AppLayout>
    )
  }

  return null
}
